Normalization

In [7]:
import seaborn as sns
import numpy as np
import pandas as pd


In [12]:
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit(df[['total_bill','tip']])


MinMaxScaler()

In [15]:
min_max.transform(df[['total_bill','tip']])

array([[0.29157939, 0.00111111],
       [0.1522832 , 0.07333333],
       [0.3757855 , 0.27777778],
       [0.43171345, 0.25666667],
       [0.45077503, 0.29      ],
       [0.46543779, 0.41222222],
       [0.11939673, 0.11111111],
       [0.49874319, 0.23555556],
       [0.25073314, 0.10666667],
       [0.24528697, 0.24777778],
       [0.15081693, 0.07888889],
       [0.67427734, 0.44444444],
       [0.25869292, 0.06333333],
       [0.32174277, 0.22222222],
       [0.24633431, 0.22444444],
       [0.38772518, 0.32444444],
       [0.15207373, 0.07444444],
       [0.27691663, 0.30111111],
       [0.29116045, 0.27777778],
       [0.36824466, 0.26111111],
       [0.31105991, 0.34222222],
       [0.36070381, 0.19444444],
       [0.2660243 , 0.13666667],
       [0.761416  , 0.73111111],
       [0.35085882, 0.24222222],
       [0.30875576, 0.14888889],
       [0.21575199, 0.11111111],
       [0.20150817, 0.11111111],
       [0.39023879, 0.36666667],
       [0.34729786, 0.22222222],
       [0.

In [19]:
min_max.fit_transform(df[['total_bill','tip']])

array([[0.29157939, 0.00111111],
       [0.1522832 , 0.07333333],
       [0.3757855 , 0.27777778],
       [0.43171345, 0.25666667],
       [0.45077503, 0.29      ],
       [0.46543779, 0.41222222],
       [0.11939673, 0.11111111],
       [0.49874319, 0.23555556],
       [0.25073314, 0.10666667],
       [0.24528697, 0.24777778],
       [0.15081693, 0.07888889],
       [0.67427734, 0.44444444],
       [0.25869292, 0.06333333],
       [0.32174277, 0.22222222],
       [0.24633431, 0.22444444],
       [0.38772518, 0.32444444],
       [0.15207373, 0.07444444],
       [0.27691663, 0.30111111],
       [0.29116045, 0.27777778],
       [0.36824466, 0.26111111],
       [0.31105991, 0.34222222],
       [0.36070381, 0.19444444],
       [0.2660243 , 0.13666667],
       [0.761416  , 0.73111111],
       [0.35085882, 0.24222222],
       [0.30875576, 0.14888889],
       [0.21575199, 0.11111111],
       [0.20150817, 0.11111111],
       [0.39023879, 0.36666667],
       [0.34729786, 0.22222222],
       [0.

In [22]:
min_max.transform([[1,3]])

c:\Users\pawan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[-0.04335987,  0.22222222]])

Unit vector

In [23]:
import seaborn  as sns
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
from sklearn.preprocessing import normalize
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [27]:
normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [28]:
import pandas as pd
pd.DataFrame(normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]),columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

sepal_length  sepal_width  petal_length  petal_width
0        0.803773     0.551609      0.220644     0.031521
1        0.828133     0.507020      0.236609     0.033801
2        0.805333     0.548312      0.222752     0.034269
3        0.800030     0.539151      0.260879     0.034784
4        0.790965     0.569495      0.221470     0.031639
..            ...          ...           ...          ...
145      0.721557     0.323085      0.560015     0.247699
146      0.729654     0.289545      0.579090     0.220054
147      0.716539     0.330710      0.573231     0.220474
148      0.674671     0.369981      0.587616     0.250281
149      0.690259     0.350979      0.596665     0.210588

[150 rows x 4 columns]